# Tempo em minutos para o lixeiro limpar tudo automaticamente
intervalo-minutos: 40

# De quantos em quantos minutos o aviso será enviado
aviso-cada-minutos: 10

# Tipos de limpeza
limpar:
  itens: true
  mobs: true
  blocos: true

# Itens que NÃO serão limpos
itens-protegidos:
  - DIAMOND
  - NETHERITE_SWORD
  - NETHER_STAR
  - DRAGON_EGG

# Mobs que SERÃO limpos (somente esses)
mobs-que-sao-limpos:
  - ZOMBIE
  - SKELETON
  - CREEPER
  - SPIDER
  - ENDERMAN
  - SLIME
  - PHANTOM
  - SILVERFISH
  - HUSK

# Blocos/Entidades físicas que SERÃO limpos
blocos-que-serao-limpos:
  # TNT ativa
  - PRIMED_TNT
  - TNT
  - TNT_MINECART

  # Barcos normais
  - OAK_BOAT
  - SPRUCE_BOAT
  - BIRCH_BOAT
  - JUNGLE_BOAT
  - ACACIA_BOAT
  - DARK_OAK_BOAT
  - MANGROVE_BOAT
  - BAMBOO_RAFT
  - CHERRY_BOAT

  # Barcos com baú
  - OAK_CHEST_BOAT
  - SPRUCE_CHEST_BOAT
  - BIRCH_CHEST_BOAT
  - JUNGLE_CHEST_BOAT
  - ACACIA_CHEST_BOAT
  - DARK_OAK_CHEST_BOAT
  - MANGROVE_CHEST_BOAT
  - BAMBOO_CHEST_RAFT
  - CHERRY_CHEST_BOAT

limites-chunk:
  mobs:
    VILLAGER: 35
  blocos:
    # Barcos
    OAK_BOAT: 5
    SPRUCE_BOAT: 5
    BIRCH_BOAT: 5
    JUNGLE_BOAT: 5
    ACACIA_BOAT: 5
    MANGROVE_BOAT: 5
    CHERRY_BOAT: 5
    DARK_OAK_BOAT: 5
    PALE_OAK_BOAT: 5

    # Minecarts
    MINECART: 5
    CHEST_MINECART: 5
    FURNACE_MINECART: 5
    TNT_MINECART: 3
    HOPPER_MINECART: 5
    SPAWNER_MINECART: 2

    # TNT ativa
    PRIMED_TNT: 3

    # Placas e armor stands
    ARMOR_STAND: 10
    SIGN: 10
    WALL_SIGN: 10
    PAINTING: 5

    # Portais (novo)
    NETHER_PORTAL: 3

    # Outros blocos/entidades físicas que podem gerar lag
    MINECART_WITH_TNT: 2

# Webhook do Discord para logs de limpeza (deixe vazio para desativar)
discord-webhook: "SUA_WEBHOOK_AQUI"
